FROM devkitpro/devkitppc:latest AS libromfs_builder
WORKDIR /libromfs

RUN git clone https://github.com/yawut/libromfs-wiiu.git . 
RUN make
RUN make install

FROM devkitpro/devkitppc:latest AS main_builder
WORKDIR /app

COPY --from=libromfs_installer /opt/devkitpro/portlibs/wiiu/ /opt/devkitpro/portlibs/wiiu/
COPY . .

RUN make PLATFORM=wiiu ENABLE_CLOUDVARS=1 ENABLE_AUDIO=1

FROM scratch AS exporter
COPY --from=main_builder /app/build/scratch-wiiu /scratch-wiiu
