FROM devkitpro/devkita64:latest AS main_builder
WORKDIR /app

COPY . .

RUN /opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-cmake -B build-nx -DCMAKE_BUILD_TYPE=Release && /opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-cmake --build build-nx

FROM scratch AS exporter
COPY --from=main_builder /app/build/scratch-nx.nro /
