FROM vitasdk/vitasdk:latest AS main_builder
WORKDIR /app

COPY . .

RUN cmake -B build-vita -DCMAKE_TOOLCHAIN_FILE=$VITASDK/share/vita.toolchain.cmake -DCMAKE_BUILD_TYPE=Release && cmake --build build-vita

FROM scratch AS exporter

COPY --from=main_builder /app/build/scratch-vita.vpk /
