FROM gcc:14 AS curl_builder

ARG CURL_VERSION=8.7.1

FROM gcc:14 AS main_builder

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

COPY . .

RUN cmake -B build -DCMAKE_BUILD_TYPE=Release && cmake --build build

FROM scratch AS exporter

COPY --from=main_builder /app/build/scratch-pc /
